PROFILE_NAMES = Default DEVICE_8dev_carambola2 DEVICE_avm_fritz4020 DEVICE_avm_fritz300e DEVICE_aruba_ap-105 DEVICE_buffalo_bhr-4grv DEVICE_buffalo_bhr-4grv2 DEVICE_buffalo_wzr-hp-ag300h DEVICE_buffalo_wzr-hp-g302h-a1a0 DEVICE_buffalo_wzr-hp-g450h DEVICE_comfast_cf-e110n-v2 DEVICE_comfast_cf-e120a-v3 DEVICE_comfast_cf-e5 DEVICE_dlink_dir-825-b1 DEVICE_dlink_dir-825-c1 DEVICE_dlink_dir-835-a1 DEVICE_dlink_dir-859-a1 DEVICE_elecom_wrc-1750ghbk2-i DEVICE_elecom_wrc-300ghbk2-i DEVICE_embeddedwireless_dorin DEVICE_engenius_ecb1750 DEVICE_engenius_epg5000 DEVICE_engenius_ews511ap DEVICE_glinet_gl-ar150 DEVICE_glinet_gl-ar300m-lite DEVICE_glinet_gl-x750 DEVICE_iodata_etg3-r DEVICE_iodata_wn-ac1167dgr DEVICE_iodata_wn-ac1600dgr DEVICE_iodata_wn-ac1600dgr2 DEVICE_iodata_wn-ag300dgr DEVICE_librerouter_librerouter-v1 DEVICE_nec_wg1200cr DEVICE_nec_wg800hp DEVICE_netgear_ex6400 DEVICE_netgear_ex7300 DEVICE_netgear_wndr3700 DEVICE_netgear_wndr3700v2 DEVICE_netgear_wndr3800 DEVICE_ocedo_koala DEVICE_ocedo_raccoon DEVICE_ocedo_ursus DEVICE_openmesh_om5p-ac-v2 DEVICE_phicomm_k2t DEVICE_pisen_wmm003n DEVICE_pcs_cap324 DEVICE_pcs_cr3000 DEVICE_pcs_cr5000 DEVICE_rosinson_wr818 DEVICE_tplink_archer-a7-v5 DEVICE_tplink_archer-c2-v3 DEVICE_tplink_archer-c25-v1 DEVICE_tplink_archer-c5-v1 DEVICE_tplink_archer-c58-v1 DEVICE_tplink_archer-c59-v1 DEVICE_tplink_archer-c6-v2 DEVICE_tplink_archer-c60-v1 DEVICE_tplink_archer-c60-v2 DEVICE_tplink_archer-c60-v3 DEVICE_tplink_archer-c7-v1 DEVICE_tplink_archer-c7-v2 DEVICE_tplink_archer-c7-v4 DEVICE_tplink_archer-c7-v5 DEVICE_tplink_archer-d50-v1 DEVICE_tplink_cpe210-v2 DEVICE_tplink_cpe210-v3 DEVICE_tplink_cpe220-v3 DEVICE_tplink_re350k-v1 DEVICE_tplink_re450-v2 DEVICE_tplink_tl-wdr3500-v1 DEVICE_tplink_tl-wdr3600-v1 DEVICE_tplink_tl-wdr4300-v1 DEVICE_tplink_tl-wdr4300-v1-il DEVICE_tplink_tl-wdr4310-v1 DEVICE_tplink_tl-wdr4900-v2 DEVICE_tplink_tl-wr1043n-v5 DEVICE_tplink_tl-wr1043nd-v1 DEVICE_tplink_tl-wr1043nd-v2 DEVICE_tplink_tl-wr1043nd-v3 DEVICE_tplink_tl-wr1043nd-v4 DEVICE_tplink_tl-wr2543-v1 DEVICE_tplink_tl-wr710n-v1 DEVICE_tplink_tl-wr710n-v2.1 DEVICE_tplink_tl-wr810n-v1 DEVICE_tplink_tl-wr810n-v2 DEVICE_tplink_tl-wr842n-v3 DEVICE_tplink_tl-wr842n-v1 DEVICE_tplink_tl-wr842n-v2 DEVICE_ubnt_airrouter DEVICE_ubnt_bullet-m DEVICE_ubnt_bullet-m-xw DEVICE_ubnt_lap-120 DEVICE_ubnt_nanobeam-ac DEVICE_ubnt_nanostation-ac DEVICE_ubnt_nanostation-ac-loco DEVICE_ubnt_nanostation-loco-m DEVICE_ubnt_nanostation-loco-m-xw DEVICE_ubnt_nanostation-m DEVICE_ubnt_nanostation-m-xw DEVICE_ubnt_picostation-m DEVICE_ubnt_rocket-m DEVICE_ubnt_routerstation DEVICE_ubnt_routerstation-pro DEVICE_ubnt_unifi DEVICE_ubnt_unifiac-lr DEVICE_ubnt_unifiac-lite DEVICE_ubnt_unifiac-mesh DEVICE_ubnt_unifiac-mesh-pro DEVICE_ubnt_unifiac-pro DEVICE_ubnt_acb-isp DEVICE_wd_mynet-n750 DEVICE_wd_mynet-wifi-rangeextender DEVICE_winchannel_wb2000 DEVICE_xiaomi_mi-router-4q DEVICE_yuncore_a770 DEVICE_yuncore_a782 DEVICE_yuncore_xd4200 DEVICE_zbtlink_zbt-wd323 DEVICE_devolo_dvl1200e DEVICE_devolo_dvl1200i DEVICE_devolo_dvl1750c DEVICE_devolo_dvl1750e DEVICE_devolo_dvl1750i DEVICE_devolo_dvl1750x DEVICE_etactica_eg200 DEVICE_jjplus_ja76pf2
Default_NAME:=Default Profile (all drivers)
Default_HAS_IMAGE_METADATA:=0
Default_PACKAGES:=iwinfo
DEVICE_8dev_carambola2_NAME:=8devices Carambola2
DEVICE_8dev_carambola2_HAS_IMAGE_METADATA:=1
DEVICE_8dev_carambola2_SUPPORTED_DEVICES:=8dev,carambola2 carambola2
DEVICE_8dev_carambola2_PACKAGES:=kmod-usb2 kmod-usb-chipidea2
DEVICE_avm_fritz4020_NAME:=AVM FRITZ!Box 4020
DEVICE_avm_fritz4020_HAS_IMAGE_METADATA:=1
DEVICE_avm_fritz4020_SUPPORTED_DEVICES:=avm,fritz4020 fritz4020
DEVICE_avm_fritz4020_PACKAGES:=fritz-tffs
DEVICE_avm_fritz300e_NAME:=AVM FRITZ!WLAN Repeater 300E
DEVICE_avm_fritz300e_HAS_IMAGE_METADATA:=1
DEVICE_avm_fritz300e_SUPPORTED_DEVICES:=avm,fritz300e fritz300e
DEVICE_avm_fritz300e_PACKAGES:=fritz-tffs rssileds -swconfig
DEVICE_aruba_ap-105_NAME:=Aruba AP-105
DEVICE_aruba_ap-105_HAS_IMAGE_METADATA:=1
DEVICE_aruba_ap-105_SUPPORTED_DEVICES:=aruba,ap-105
DEVICE_aruba_ap-105_PACKAGES:=kmod-i2c-core kmod-i2c-gpio kmod-tpm-i2c-atmel
DEVICE_buffalo_bhr-4grv_NAME:=Buffalo BHR-4GRV
DEVICE_buffalo_bhr-4grv_HAS_IMAGE_METADATA:=1
DEVICE_buffalo_bhr-4grv_SUPPORTED_DEVICES:=buffalo,bhr-4grv wzr-hp-g450h
DEVICE_buffalo_bhr-4grv_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_buffalo_bhr-4grv2_NAME:=Buffalo BHR-4GRV2
DEVICE_buffalo_bhr-4grv2_HAS_IMAGE_METADATA:=1
DEVICE_buffalo_bhr-4grv2_SUPPORTED_DEVICES:=buffalo,bhr-4grv2
DEVICE_buffalo_bhr-4grv2_PACKAGES:=
DEVICE_buffalo_wzr-hp-ag300h_NAME:=Buffalo WZR-HP-AG300H
DEVICE_buffalo_wzr-hp-ag300h_HAS_IMAGE_METADATA:=1
DEVICE_buffalo_wzr-hp-ag300h_SUPPORTED_DEVICES:=buffalo,wzr-hp-ag300h wzr-hp-ag300h
DEVICE_buffalo_wzr-hp-ag300h_PACKAGES:=kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb-ledtrig-usbport kmod-leds-reset kmod-owl-loader
DEVICE_buffalo_wzr-hp-g302h-a1a0_NAME:=Buffalo WZR-HP-G302H A1A0
DEVICE_buffalo_wzr-hp-g302h-a1a0_HAS_IMAGE_METADATA:=1
DEVICE_buffalo_wzr-hp-g302h-a1a0_SUPPORTED_DEVICES:=buffalo,wzr-hp-g302h-a1a0 wzr-hp-g300nh2
DEVICE_buffalo_wzr-hp-g302h-a1a0_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_buffalo_wzr-hp-g450h_NAME:=Buffalo WZR-HP-G450H/WZR-450HP
DEVICE_buffalo_wzr-hp-g450h_HAS_IMAGE_METADATA:=1
DEVICE_buffalo_wzr-hp-g450h_SUPPORTED_DEVICES:=buffalo,wzr-hp-g450h wzr-hp-g450h
DEVICE_buffalo_wzr-hp-g450h_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_comfast_cf-e110n-v2_NAME:=COMFAST CF-E110N v2
DEVICE_comfast_cf-e110n-v2_HAS_IMAGE_METADATA:=1
DEVICE_comfast_cf-e110n-v2_SUPPORTED_DEVICES:=comfast,cf-e110n-v2
DEVICE_comfast_cf-e110n-v2_PACKAGES:=rssileds kmod-leds-gpio -swconfig -uboot-envtools
DEVICE_comfast_cf-e120a-v3_NAME:=COMFAST CF-E120A v3
DEVICE_comfast_cf-e120a-v3_HAS_IMAGE_METADATA:=1
DEVICE_comfast_cf-e120a-v3_SUPPORTED_DEVICES:=comfast,cf-e120a-v3
DEVICE_comfast_cf-e120a-v3_PACKAGES:=rssileds kmod-leds-gpio -uboot-envtools
DEVICE_comfast_cf-e5_NAME:=COMFAST CF-E5/E7
DEVICE_comfast_cf-e5_HAS_IMAGE_METADATA:=1
DEVICE_comfast_cf-e5_SUPPORTED_DEVICES:=comfast,cf-e5
DEVICE_comfast_cf-e5_PACKAGES:=rssileds kmod-leds-gpio kmod-usb-core kmod-usb2 kmod-usb-net kmod-usb-net-qmi-wwan -swconfig -uboot-envtools
DEVICE_dlink_dir-825-b1_NAME:=D-LINK DIR-825 B1
DEVICE_dlink_dir-825-b1_HAS_IMAGE_METADATA:=1
DEVICE_dlink_dir-825-b1_SUPPORTED_DEVICES:=dlink,dir-825-b1 dir-825-b1
DEVICE_dlink_dir-825-b1_PACKAGES:=kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb-ledtrig-usbport kmod-leds-reset kmod-owl-loader
DEVICE_dlink_dir-825-c1_NAME:=D-LINK DIR-825 C1
DEVICE_dlink_dir-825-c1_HAS_IMAGE_METADATA:=1
DEVICE_dlink_dir-825-c1_SUPPORTED_DEVICES:=dlink,dir-825-c1 dir-825-c1
DEVICE_dlink_dir-825-c1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-leds-reset kmod-owl-loader
DEVICE_dlink_dir-835-a1_NAME:=D-LINK DIR-835 A1
DEVICE_dlink_dir-835-a1_HAS_IMAGE_METADATA:=1
DEVICE_dlink_dir-835-a1_SUPPORTED_DEVICES:=dlink,dir-835-a1 dir-835-a1
DEVICE_dlink_dir-835-a1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-leds-reset kmod-owl-loader
DEVICE_dlink_dir-859-a1_NAME:=D-LINK DIR-859 A1
DEVICE_dlink_dir-859-a1_HAS_IMAGE_METADATA:=1
DEVICE_dlink_dir-859-a1_SUPPORTED_DEVICES:=dlink,dir-859-a1
DEVICE_dlink_dir-859-a1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct-smallbuffers ath10k-firmware-qca988x-ct
DEVICE_elecom_wrc-1750ghbk2-i_NAME:=ELECOM WRC-1750GHBK2-I/C
DEVICE_elecom_wrc-1750ghbk2-i_HAS_IMAGE_METADATA:=1
DEVICE_elecom_wrc-1750ghbk2-i_SUPPORTED_DEVICES:=elecom,wrc-1750ghbk2-i
DEVICE_elecom_wrc-1750ghbk2-i_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_elecom_wrc-300ghbk2-i_NAME:=ELECOM WRC-300GHBK2-I
DEVICE_elecom_wrc-300ghbk2-i_HAS_IMAGE_METADATA:=1
DEVICE_elecom_wrc-300ghbk2-i_SUPPORTED_DEVICES:=elecom,wrc-300ghbk2-i
DEVICE_elecom_wrc-300ghbk2-i_PACKAGES:=
DEVICE_embeddedwireless_dorin_NAME:=Embedded Wireless Dorin
DEVICE_embeddedwireless_dorin_HAS_IMAGE_METADATA:=1
DEVICE_embeddedwireless_dorin_SUPPORTED_DEVICES:=embeddedwireless,dorin
DEVICE_embeddedwireless_dorin_PACKAGES:=kmod-usb-chipidea2
DEVICE_engenius_ecb1750_NAME:=EnGenius ECB1750
DEVICE_engenius_ecb1750_HAS_IMAGE_METADATA:=1
DEVICE_engenius_ecb1750_SUPPORTED_DEVICES:=engenius,ecb1750
DEVICE_engenius_ecb1750_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_engenius_epg5000_NAME:=EnGenius EPG5000
DEVICE_engenius_epg5000_HAS_IMAGE_METADATA:=1
DEVICE_engenius_epg5000_SUPPORTED_DEVICES:=engenius,epg5000 epg5000
DEVICE_engenius_epg5000_PACKAGES:=ath10k-firmware-qca988x-ct kmod-ath10k-ct kmod-usb2
DEVICE_engenius_ews511ap_NAME:=EnGenius EWS511AP
DEVICE_engenius_ews511ap_HAS_IMAGE_METADATA:=1
DEVICE_engenius_ews511ap_SUPPORTED_DEVICES:=engenius,ews511ap
DEVICE_engenius_ews511ap_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca9887-ct
DEVICE_glinet_gl-ar150_NAME:=GL.iNet GL-AR150
DEVICE_glinet_gl-ar150_HAS_IMAGE_METADATA:=1
DEVICE_glinet_gl-ar150_SUPPORTED_DEVICES:=glinet,gl-ar150 gl-ar150
DEVICE_glinet_gl-ar150_PACKAGES:=kmod-usb-chipidea2
DEVICE_glinet_gl-ar300m-lite_NAME:=GL.iNet GL-AR300M-Lite
DEVICE_glinet_gl-ar300m-lite_HAS_IMAGE_METADATA:=1
DEVICE_glinet_gl-ar300m-lite_SUPPORTED_DEVICES:=glinet,gl-ar300m-lite gl-ar300m
DEVICE_glinet_gl-ar300m-lite_PACKAGES:=kmod-usb-core kmod-usb2
DEVICE_glinet_gl-x750_NAME:=GL.iNet GL-X750
DEVICE_glinet_gl-x750_HAS_IMAGE_METADATA:=1
DEVICE_glinet_gl-x750_SUPPORTED_DEVICES:=glinet,gl-x750
DEVICE_glinet_gl-x750_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct ath10k-firmware-qca9887-ct
DEVICE_iodata_etg3-r_NAME:=I-O DATA ETG3-R
DEVICE_iodata_etg3-r_HAS_IMAGE_METADATA:=1
DEVICE_iodata_etg3-r_SUPPORTED_DEVICES:=iodata,etg3-r
DEVICE_iodata_etg3-r_PACKAGES:=-iwinfo -kmod-ath9k -wpad-basic
DEVICE_iodata_wn-ac1167dgr_NAME:=I-O DATA WN-AC1167DGR
DEVICE_iodata_wn-ac1167dgr_HAS_IMAGE_METADATA:=1
DEVICE_iodata_wn-ac1167dgr_SUPPORTED_DEVICES:=iodata,wn-ac1167dgr
DEVICE_iodata_wn-ac1167dgr_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_iodata_wn-ac1600dgr_NAME:=I-O DATA WN-AC1600DGR
DEVICE_iodata_wn-ac1600dgr_HAS_IMAGE_METADATA:=1
DEVICE_iodata_wn-ac1600dgr_SUPPORTED_DEVICES:=iodata,wn-ac1600dgr
DEVICE_iodata_wn-ac1600dgr_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_iodata_wn-ac1600dgr2_NAME:=I-O DATA WN-AC1600DGR2
DEVICE_iodata_wn-ac1600dgr2_HAS_IMAGE_METADATA:=1
DEVICE_iodata_wn-ac1600dgr2_SUPPORTED_DEVICES:=iodata,wn-ac1600dgr2
DEVICE_iodata_wn-ac1600dgr2_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_iodata_wn-ag300dgr_NAME:=I-O DATA WN-AG300DGR
DEVICE_iodata_wn-ag300dgr_HAS_IMAGE_METADATA:=1
DEVICE_iodata_wn-ag300dgr_SUPPORTED_DEVICES:=iodata,wn-ag300dgr
DEVICE_iodata_wn-ag300dgr_PACKAGES:=kmod-usb-core kmod-usb2
DEVICE_librerouter_librerouter-v1_NAME:=LibreRouter v1
DEVICE_librerouter_librerouter-v1_HAS_IMAGE_METADATA:=1
DEVICE_librerouter_librerouter-v1_SUPPORTED_DEVICES:=librerouter,librerouter-v1
DEVICE_librerouter_librerouter-v1_PACKAGES:=kmod-usb-core kmod-usb2
DEVICE_nec_wg1200cr_NAME:=NEC Aterm WG1200CR
DEVICE_nec_wg1200cr_HAS_IMAGE_METADATA:=1
DEVICE_nec_wg1200cr_SUPPORTED_DEVICES:=nec,wg1200cr
DEVICE_nec_wg1200cr_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca9888-ct
DEVICE_nec_wg800hp_NAME:=NEC Aterm WG800HP
DEVICE_nec_wg800hp_HAS_IMAGE_METADATA:=1
DEVICE_nec_wg800hp_SUPPORTED_DEVICES:=nec,wg800hp
DEVICE_nec_wg800hp_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9887-ct-htt
DEVICE_netgear_ex6400_NAME:=NETGEAR EX6400
DEVICE_netgear_ex6400_HAS_IMAGE_METADATA:=1
DEVICE_netgear_ex6400_SUPPORTED_DEVICES:=netgear,ex6400
DEVICE_netgear_ex6400_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca99x0-ct
DEVICE_netgear_ex7300_NAME:=NETGEAR EX7300
DEVICE_netgear_ex7300_HAS_IMAGE_METADATA:=1
DEVICE_netgear_ex7300_SUPPORTED_DEVICES:=netgear,ex7300
DEVICE_netgear_ex7300_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca99x0-ct
DEVICE_netgear_wndr3700_NAME:=NETGEAR WNDR3700
DEVICE_netgear_wndr3700_HAS_IMAGE_METADATA:=1
DEVICE_netgear_wndr3700_SUPPORTED_DEVICES:=netgear,wndr3700 wndr3700
DEVICE_netgear_wndr3700_PACKAGES:=kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb-ledtrig-usbport kmod-leds-reset kmod-owl-loader
DEVICE_netgear_wndr3700v2_NAME:=NETGEAR WNDR3700v2
DEVICE_netgear_wndr3700v2_HAS_IMAGE_METADATA:=1
DEVICE_netgear_wndr3700v2_SUPPORTED_DEVICES:=netgear,wndr3700v2 wndr3700
DEVICE_netgear_wndr3700v2_PACKAGES:=kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb-ledtrig-usbport kmod-leds-reset kmod-owl-loader
DEVICE_netgear_wndr3800_NAME:=NETGEAR WNDR3800
DEVICE_netgear_wndr3800_HAS_IMAGE_METADATA:=1
DEVICE_netgear_wndr3800_SUPPORTED_DEVICES:=netgear,wndr3800 wndr3700
DEVICE_netgear_wndr3800_PACKAGES:=kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb-ledtrig-usbport kmod-leds-reset kmod-owl-loader
DEVICE_ocedo_koala_NAME:=OCEDO Koala
DEVICE_ocedo_koala_HAS_IMAGE_METADATA:=1
DEVICE_ocedo_koala_SUPPORTED_DEVICES:=ocedo,koala koala
DEVICE_ocedo_koala_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_ocedo_raccoon_NAME:=OCEDO Raccoon
DEVICE_ocedo_raccoon_HAS_IMAGE_METADATA:=1
DEVICE_ocedo_raccoon_SUPPORTED_DEVICES:=ocedo,raccoon
DEVICE_ocedo_raccoon_PACKAGES:=
DEVICE_ocedo_ursus_NAME:=OCEDO Ursus
DEVICE_ocedo_ursus_HAS_IMAGE_METADATA:=1
DEVICE_ocedo_ursus_SUPPORTED_DEVICES:=ocedo,ursus
DEVICE_ocedo_ursus_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_openmesh_om5p-ac-v2_NAME:=OpenMesh OM5P-AC v2
DEVICE_openmesh_om5p-ac-v2_HAS_IMAGE_METADATA:=1
DEVICE_openmesh_om5p-ac-v2_SUPPORTED_DEVICES:=openmesh,om5p-ac-v2 om5p-acv2
DEVICE_openmesh_om5p-ac-v2_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct om-watchdog
DEVICE_phicomm_k2t_NAME:=Phicomm K2T
DEVICE_phicomm_k2t_HAS_IMAGE_METADATA:=1
DEVICE_phicomm_k2t_SUPPORTED_DEVICES:=phicomm,k2t
DEVICE_phicomm_k2t_PACKAGES:=kmod-leds-reset kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9888-ct
DEVICE_pisen_wmm003n_NAME:=Pisen WMM003N (Cloud Easy Power)
DEVICE_pisen_wmm003n_HAS_IMAGE_METADATA:=1
DEVICE_pisen_wmm003n_SUPPORTED_DEVICES:=pisen,wmm003n
DEVICE_pisen_wmm003n_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-chipidea2
DEVICE_pcs_cap324_NAME:=PowerCloud Systems CAP324
DEVICE_pcs_cap324_HAS_IMAGE_METADATA:=1
DEVICE_pcs_cap324_SUPPORTED_DEVICES:=pcs,cap324 cap324
DEVICE_pcs_cap324_PACKAGES:=
DEVICE_pcs_cr3000_NAME:=PowerCloud Systems CR3000
DEVICE_pcs_cr3000_HAS_IMAGE_METADATA:=1
DEVICE_pcs_cr3000_SUPPORTED_DEVICES:=pcs,cr3000 cr3000
DEVICE_pcs_cr3000_PACKAGES:=
DEVICE_pcs_cr5000_NAME:=PowerCloud Systems CR5000
DEVICE_pcs_cr5000_HAS_IMAGE_METADATA:=1
DEVICE_pcs_cr5000_SUPPORTED_DEVICES:=pcs,cr5000 cr5000
DEVICE_pcs_cr5000_PACKAGES:=kmod-usb2 kmod-usb-core
DEVICE_rosinson_wr818_NAME:=ROSINSON WR818
DEVICE_rosinson_wr818_HAS_IMAGE_METADATA:=1
DEVICE_rosinson_wr818_SUPPORTED_DEVICES:=rosinson,wr818
DEVICE_rosinson_wr818_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_archer-a7-v5_NAME:=TP-Link Archer A7 v5
DEVICE_tplink_archer-a7-v5_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-a7-v5_SUPPORTED_DEVICES:=tplink,archer-a7-v5
DEVICE_tplink_archer-a7-v5_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_tplink_archer-c2-v3_NAME:=TP-Link Archer C2 v3
DEVICE_tplink_archer-c2-v3_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c2-v3_SUPPORTED_DEVICES:=tplink,archer-c2-v3
DEVICE_tplink_archer-c2-v3_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9887-ct
DEVICE_tplink_archer-c25-v1_NAME:=TP-Link Archer C25 v1
DEVICE_tplink_archer-c25-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c25-v1_SUPPORTED_DEVICES:=tplink,archer-c25-v1 archer-c25-v1
DEVICE_tplink_archer-c25-v1_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9887-ct
DEVICE_tplink_archer-c5-v1_NAME:=TP-Link Archer C5 v1
DEVICE_tplink_archer-c5-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c5-v1_SUPPORTED_DEVICES:=tplink,archer-c5-v1 archer-c5
DEVICE_tplink_archer-c5-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_tplink_archer-c58-v1_NAME:=TP-Link Archer C58 v1
DEVICE_tplink_archer-c58-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c58-v1_SUPPORTED_DEVICES:=tplink,archer-c58-v1 archer-c58-v1
DEVICE_tplink_archer-c58-v1_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9888-ct
DEVICE_tplink_archer-c59-v1_NAME:=TP-Link Archer C59 v1
DEVICE_tplink_archer-c59-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c59-v1_SUPPORTED_DEVICES:=tplink,archer-c59-v1 archer-c59-v1
DEVICE_tplink_archer-c59-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-ath10k-ct ath10k-firmware-qca9888-ct
DEVICE_tplink_archer-c6-v2_NAME:=TP-Link Archer C6 v2
DEVICE_tplink_archer-c6-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c6-v2_SUPPORTED_DEVICES:=tplink,archer-c6-v2
DEVICE_tplink_archer-c6-v2_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca9888-ct
DEVICE_tplink_archer-c60-v1_NAME:=TP-Link Archer C60 v1
DEVICE_tplink_archer-c60-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c60-v1_SUPPORTED_DEVICES:=tplink,archer-c60-v1 archer-c60-v1
DEVICE_tplink_archer-c60-v1_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9888-ct
DEVICE_tplink_archer-c60-v2_NAME:=TP-Link Archer C60 v2
DEVICE_tplink_archer-c60-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c60-v2_SUPPORTED_DEVICES:=tplink,archer-c60-v2 archer-c60-v2
DEVICE_tplink_archer-c60-v2_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9888-ct
DEVICE_tplink_archer-c60-v3_NAME:=TP-Link Archer C60 v3
DEVICE_tplink_archer-c60-v3_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c60-v3_SUPPORTED_DEVICES:=tplink,archer-c60-v3
DEVICE_tplink_archer-c60-v3_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca9888-ct
DEVICE_tplink_archer-c7-v1_NAME:=TP-Link Archer C7 v1
DEVICE_tplink_archer-c7-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c7-v1_SUPPORTED_DEVICES:=tplink,archer-c7-v1 archer-c7
DEVICE_tplink_archer-c7-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_archer-c7-v2_NAME:=TP-Link Archer C7 v2
DEVICE_tplink_archer-c7-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c7-v2_SUPPORTED_DEVICES:=tplink,archer-c7-v2 archer-c7
DEVICE_tplink_archer-c7-v2_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_tplink_archer-c7-v4_NAME:=TP-Link Archer C7 v4
DEVICE_tplink_archer-c7-v4_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c7-v4_SUPPORTED_DEVICES:=tplink,archer-c7-v4 archer-c7-v4
DEVICE_tplink_archer-c7-v4_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_tplink_archer-c7-v5_NAME:=TP-Link Archer C7 v5
DEVICE_tplink_archer-c7-v5_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-c7-v5_SUPPORTED_DEVICES:=tplink,archer-c7-v5 archer-c7-v5
DEVICE_tplink_archer-c7-v5_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_tplink_archer-d50-v1_NAME:=TP-Link Archer D50 v1
DEVICE_tplink_archer-d50-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_archer-d50-v1_SUPPORTED_DEVICES:=tplink,archer-d50-v1
DEVICE_tplink_archer-d50-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport kmod-ath10k-ct-smallbuffers ath10k-firmware-qca988x-ct
DEVICE_tplink_cpe210-v2_NAME:=TP-Link CPE210 v2
DEVICE_tplink_cpe210-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_cpe210-v2_SUPPORTED_DEVICES:=tplink,cpe210-v2 cpe210-v2
DEVICE_tplink_cpe210-v2_PACKAGES:=rssileds
DEVICE_tplink_cpe210-v3_NAME:=TP-Link CPE210 v3
DEVICE_tplink_cpe210-v3_HAS_IMAGE_METADATA:=1
DEVICE_tplink_cpe210-v3_SUPPORTED_DEVICES:=tplink,cpe210-v3 cpe210-v3
DEVICE_tplink_cpe210-v3_PACKAGES:=rssileds
DEVICE_tplink_cpe220-v3_NAME:=TP-Link CPE220 v3
DEVICE_tplink_cpe220-v3_HAS_IMAGE_METADATA:=1
DEVICE_tplink_cpe220-v3_SUPPORTED_DEVICES:=tplink,cpe220-v3
DEVICE_tplink_cpe220-v3_PACKAGES:=rssileds
DEVICE_tplink_re350k-v1_NAME:=TP-Link RE350K v1
DEVICE_tplink_re350k-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_re350k-v1_SUPPORTED_DEVICES:=tplink,re350k-v1
DEVICE_tplink_re350k-v1_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_tplink_re450-v2_NAME:=TP-Link RE450 v2
DEVICE_tplink_re450-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_re450-v2_SUPPORTED_DEVICES:=tplink,re450-v2
DEVICE_tplink_re450-v2_PACKAGES:=kmod-ath10k-ct-smallbuffers ath10k-firmware-qca988x-ct
DEVICE_tplink_tl-wdr3500-v1_NAME:=TP-Link TL-WDR3500 v1
DEVICE_tplink_tl-wdr3500-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wdr3500-v1_SUPPORTED_DEVICES:=tplink,tl-wdr3500-v1 tl-wdr3500
DEVICE_tplink_tl-wdr3500-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wdr3600-v1_NAME:=TP-Link TL-WDR3600 v1
DEVICE_tplink_tl-wdr3600-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wdr3600-v1_SUPPORTED_DEVICES:=tplink,tl-wdr3600-v1 tl-wdr4300
DEVICE_tplink_tl-wdr3600-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wdr4300-v1_NAME:=TP-Link TL-WDR4300 v1
DEVICE_tplink_tl-wdr4300-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wdr4300-v1_SUPPORTED_DEVICES:=tplink,tl-wdr4300-v1 tl-wdr4300
DEVICE_tplink_tl-wdr4300-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wdr4300-v1-il_NAME:=TP-Link TL-WDR4300 v1 (IL)
DEVICE_tplink_tl-wdr4300-v1-il_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wdr4300-v1-il_SUPPORTED_DEVICES:=tplink,tl-wdr4300-v1-il tl-wdr4300
DEVICE_tplink_tl-wdr4300-v1-il_PACKAGES:=kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wdr4310-v1_NAME:=TP-Link TL-WDR4310 v1
DEVICE_tplink_tl-wdr4310-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wdr4310-v1_SUPPORTED_DEVICES:=tplink,tl-wdr4310-v1 tl-wdr4300
DEVICE_tplink_tl-wdr4310-v1_PACKAGES:=kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wdr4900-v2_NAME:=TP-Link TL-WDR4900 v2
DEVICE_tplink_tl-wdr4900-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wdr4900-v2_SUPPORTED_DEVICES:=tplink,tl-wdr4900-v2 tl-wdr4900-v2
DEVICE_tplink_tl-wdr4900-v2_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr1043n-v5_NAME:=TP-Link TL-WR1043N v5
DEVICE_tplink_tl-wr1043n-v5_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr1043n-v5_SUPPORTED_DEVICES:=tplink,tl-wr1043n-v5 tl-wr1043n-v5
DEVICE_tplink_tl-wr1043n-v5_PACKAGES:=
DEVICE_tplink_tl-wr1043nd-v1_NAME:=TP-Link TL-WR1043N/ND v1
DEVICE_tplink_tl-wr1043nd-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr1043nd-v1_SUPPORTED_DEVICES:=tplink,tl-wr1043nd-v1 tl-wr1043nd
DEVICE_tplink_tl-wr1043nd-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr1043nd-v2_NAME:=TP-Link TL-WR1043N/ND v2
DEVICE_tplink_tl-wr1043nd-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr1043nd-v2_SUPPORTED_DEVICES:=tplink,tl-wr1043nd-v2 tl-wr1043nd-v2
DEVICE_tplink_tl-wr1043nd-v2_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr1043nd-v3_NAME:=TP-Link TL-WR1043N/ND v3
DEVICE_tplink_tl-wr1043nd-v3_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr1043nd-v3_SUPPORTED_DEVICES:=tplink,tl-wr1043nd-v3 tl-wr1043nd-v2
DEVICE_tplink_tl-wr1043nd-v3_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr1043nd-v4_NAME:=TP-Link TL-WR1043N/ND v4
DEVICE_tplink_tl-wr1043nd-v4_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr1043nd-v4_SUPPORTED_DEVICES:=tplink,tl-wr1043nd-v4 tl-wr1043nd-v4
DEVICE_tplink_tl-wr1043nd-v4_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr2543-v1_NAME:=TP-Link TL-WR2543N/ND v1
DEVICE_tplink_tl-wr2543-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr2543-v1_SUPPORTED_DEVICES:=tplink,tl-wr2543-v1 tl-wr2543n
DEVICE_tplink_tl-wr2543-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr710n-v1_NAME:=TP-Link TL-WR710N v1
DEVICE_tplink_tl-wr710n-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr710n-v1_SUPPORTED_DEVICES:=tplink,tl-wr710n-v1 tl-wr710n
DEVICE_tplink_tl-wr710n-v1_PACKAGES:=kmod-usb-core kmod-usb-chipidea2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr710n-v2.1_NAME:=TP-Link TL-WR710N v2.1
DEVICE_tplink_tl-wr710n-v2.1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr710n-v2.1_SUPPORTED_DEVICES:=tplink,tl-wr710n-v2.1 tl-wr710n
DEVICE_tplink_tl-wr710n-v2.1_PACKAGES:=kmod-usb-core kmod-usb-chipidea2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr810n-v1_NAME:=TP-Link TL-WR810N v1
DEVICE_tplink_tl-wr810n-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr810n-v1_SUPPORTED_DEVICES:=tplink,tl-wr810n-v1 tl-wr810n
DEVICE_tplink_tl-wr810n-v1_PACKAGES:=kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr810n-v2_NAME:=TP-Link TL-WR810N v2
DEVICE_tplink_tl-wr810n-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr810n-v2_SUPPORTED_DEVICES:=tplink,tl-wr810n-v2 tl-wr810n-v2
DEVICE_tplink_tl-wr810n-v2_PACKAGES:=
DEVICE_tplink_tl-wr842n-v3_NAME:=TP-Link TL-WR842N v3
DEVICE_tplink_tl-wr842n-v3_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr842n-v3_SUPPORTED_DEVICES:=tplink,tl-wr842n-v3 tl-wr842n-v3
DEVICE_tplink_tl-wr842n-v3_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr842n-v1_NAME:=TP-Link TL-WR842N/ND v1
DEVICE_tplink_tl-wr842n-v1_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr842n-v1_SUPPORTED_DEVICES:=tplink,tl-wr842n-v1 tl-mr3420
DEVICE_tplink_tl-wr842n-v1_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_tplink_tl-wr842n-v2_NAME:=TP-Link TL-WR842N/ND v2
DEVICE_tplink_tl-wr842n-v2_HAS_IMAGE_METADATA:=1
DEVICE_tplink_tl-wr842n-v2_SUPPORTED_DEVICES:=tplink,tl-wr842n-v2 tl-wr842n-v2
DEVICE_tplink_tl-wr842n-v2_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_ubnt_airrouter_NAME:=Ubiquiti AirRouter
DEVICE_ubnt_airrouter_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_airrouter_SUPPORTED_DEVICES:=ubnt,airrouter airrouter
DEVICE_ubnt_airrouter_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ohci
DEVICE_ubnt_bullet-m_NAME:=Ubiquiti Bullet-M
DEVICE_ubnt_bullet-m_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_bullet-m_SUPPORTED_DEVICES:=ubnt,bullet-m bullet-m
DEVICE_ubnt_bullet-m_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ohci rssileds
DEVICE_ubnt_bullet-m-xw_NAME:=Ubiquiti Bullet-M (XW)
DEVICE_ubnt_bullet-m-xw_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_bullet-m-xw_SUPPORTED_DEVICES:=ubnt,bullet-m-xw bullet-m-xw
DEVICE_ubnt_bullet-m-xw_PACKAGES:=kmod-usb-core kmod-usb2 rssileds
DEVICE_ubnt_lap-120_NAME:=Ubiquiti LiteAP ac (LAP-120)
DEVICE_ubnt_lap-120_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_lap-120_SUPPORTED_DEVICES:=ubnt,lap-120
DEVICE_ubnt_lap-120_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct-smallbuffers ath10k-firmware-qca988x-ct
DEVICE_ubnt_nanobeam-ac_NAME:=Ubiquiti NanoBeam AC
DEVICE_ubnt_nanobeam-ac_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_nanobeam-ac_SUPPORTED_DEVICES:=ubnt,nanobeam-ac
DEVICE_ubnt_nanobeam-ac_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct-smallbuffers ath10k-firmware-qca988x-ct rssileds
DEVICE_ubnt_nanostation-ac_NAME:=Ubiquiti Nanostation AC
DEVICE_ubnt_nanostation-ac_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_nanostation-ac_SUPPORTED_DEVICES:=ubnt,nanostation-ac
DEVICE_ubnt_nanostation-ac_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct-smallbuffers ath10k-firmware-qca988x-ct rssileds
DEVICE_ubnt_nanostation-ac-loco_NAME:=Ubiquiti Nanostation AC loco
DEVICE_ubnt_nanostation-ac-loco_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_nanostation-ac-loco_SUPPORTED_DEVICES:=ubnt,nanostation-ac-loco
DEVICE_ubnt_nanostation-ac-loco_PACKAGES:=kmod-usb-core kmod-usb2 kmod-ath10k-ct-smallbuffers ath10k-firmware-qca988x-ct
DEVICE_ubnt_nanostation-loco-m_NAME:=Ubiquiti Nanostation Loco M
DEVICE_ubnt_nanostation-loco-m_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_nanostation-loco-m_SUPPORTED_DEVICES:=ubnt,nanostation-loco-m bullet-m
DEVICE_ubnt_nanostation-loco-m_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ohci rssileds
DEVICE_ubnt_nanostation-loco-m-xw_NAME:=Ubiquiti Nanostation Loco M (XW)
DEVICE_ubnt_nanostation-loco-m-xw_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_nanostation-loco-m-xw_SUPPORTED_DEVICES:=ubnt,nanostation-loco-m-xw loco-m-xw
DEVICE_ubnt_nanostation-loco-m-xw_PACKAGES:=kmod-usb-core kmod-usb2 rssileds
DEVICE_ubnt_nanostation-m_NAME:=Ubiquiti Nanostation M
DEVICE_ubnt_nanostation-m_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_nanostation-m_SUPPORTED_DEVICES:=ubnt,nanostation-m nanostation-m
DEVICE_ubnt_nanostation-m_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ohci rssileds
DEVICE_ubnt_nanostation-m-xw_NAME:=Ubiquiti Nanostation M (XW)
DEVICE_ubnt_nanostation-m-xw_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_nanostation-m-xw_SUPPORTED_DEVICES:=ubnt,nanostation-m-xw nanostation-m-xw
DEVICE_ubnt_nanostation-m-xw_PACKAGES:=kmod-usb-core kmod-usb2 rssileds
DEVICE_ubnt_picostation-m_NAME:=Ubiquiti Picostation M
DEVICE_ubnt_picostation-m_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_picostation-m_SUPPORTED_DEVICES:=ubnt,picostation-m bullet-m
DEVICE_ubnt_picostation-m_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ohci rssileds
DEVICE_ubnt_rocket-m_NAME:=Ubiquiti Rocket-M
DEVICE_ubnt_rocket-m_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_rocket-m_SUPPORTED_DEVICES:=ubnt,rocket-m rocket-m
DEVICE_ubnt_rocket-m_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ohci rssileds
DEVICE_ubnt_routerstation_NAME:=Ubiquiti RouterStation
DEVICE_ubnt_routerstation_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_routerstation_SUPPORTED_DEVICES:=ubnt,routerstation routerstation
DEVICE_ubnt_routerstation_PACKAGES:=-kmod-ath9k -wpad-mini -uboot-envtools kmod-usb-ohci kmod-usb2 fconfig -swconfig
DEVICE_ubnt_routerstation-pro_NAME:=Ubiquiti RouterStation Pro
DEVICE_ubnt_routerstation-pro_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_routerstation-pro_SUPPORTED_DEVICES:=ubnt,routerstation-pro routerstation-pro
DEVICE_ubnt_routerstation-pro_PACKAGES:=-kmod-ath9k -wpad-mini -uboot-envtools kmod-usb-ohci kmod-usb2 fconfig
DEVICE_ubnt_unifi_NAME:=Ubiquiti UniFi
DEVICE_ubnt_unifi_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_unifi_SUPPORTED_DEVICES:=ubnt,unifi unifi
DEVICE_ubnt_unifi_PACKAGES:=kmod-usb-core kmod-usb2
DEVICE_ubnt_unifiac-lr_NAME:=Ubiquiti UniFi AC-LR
DEVICE_ubnt_unifiac-lr_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_unifiac-lr_SUPPORTED_DEVICES:=ubnt,unifiac-lr unifiac-lite ubnt,unifiac-lite
DEVICE_ubnt_unifiac-lr_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_ubnt_unifiac-lite_NAME:=Ubiquiti UniFi AC-Lite
DEVICE_ubnt_unifiac-lite_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_unifiac-lite_SUPPORTED_DEVICES:=ubnt,unifiac-lite unifiac-lite
DEVICE_ubnt_unifiac-lite_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_ubnt_unifiac-mesh_NAME:=Ubiquiti UniFi AC-Mesh
DEVICE_ubnt_unifiac-mesh_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_unifiac-mesh_SUPPORTED_DEVICES:=ubnt,unifiac-mesh unifiac-lite
DEVICE_ubnt_unifiac-mesh_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_ubnt_unifiac-mesh-pro_NAME:=Ubiquiti UniFi AC-Mesh Pro
DEVICE_ubnt_unifiac-mesh-pro_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_unifiac-mesh-pro_SUPPORTED_DEVICES:=ubnt,unifiac-mesh-pro unifiac-pro
DEVICE_ubnt_unifiac-mesh-pro_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_ubnt_unifiac-pro_NAME:=Ubiquiti UniFi AC-Pro
DEVICE_ubnt_unifiac-pro_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_unifiac-pro_SUPPORTED_DEVICES:=ubnt,unifiac-pro unifiac-pro
DEVICE_ubnt_unifiac-pro_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct kmod-usb-core kmod-usb2
DEVICE_ubnt_acb-isp_NAME:=Ubiquiti airCube ISP
DEVICE_ubnt_acb-isp_HAS_IMAGE_METADATA:=1
DEVICE_ubnt_acb-isp_SUPPORTED_DEVICES:=ubnt,acb-isp
DEVICE_ubnt_acb-isp_PACKAGES:=kmod-usb-core kmod-usb2
DEVICE_wd_mynet-n750_NAME:=Western Digital My Net N750
DEVICE_wd_mynet-n750_HAS_IMAGE_METADATA:=1
DEVICE_wd_mynet-n750_SUPPORTED_DEVICES:=wd,mynet-n750 mynet-n750
DEVICE_wd_mynet-n750_PACKAGES:=kmod-usb-core kmod-usb2
DEVICE_wd_mynet-wifi-rangeextender_NAME:=Western Digital My Net Wi-Fi Range Extender
DEVICE_wd_mynet-wifi-rangeextender_HAS_IMAGE_METADATA:=1
DEVICE_wd_mynet-wifi-rangeextender_SUPPORTED_DEVICES:=wd,mynet-wifi-rangeextender mynet-rext
DEVICE_wd_mynet-wifi-rangeextender_PACKAGES:=rssileds nvram -swconfig
DEVICE_winchannel_wb2000_NAME:=Winchannel WB2000
DEVICE_winchannel_wb2000_HAS_IMAGE_METADATA:=1
DEVICE_winchannel_wb2000_SUPPORTED_DEVICES:=winchannel,wb2000
DEVICE_winchannel_wb2000_PACKAGES:=kmod-i2c-core kmod-i2c-gpio kmod-rtc-ds1307 kmod-usb2 kmod-usb-ledtrig-usbport
DEVICE_xiaomi_mi-router-4q_NAME:=Xiaomi Mi Router 4Q
DEVICE_xiaomi_mi-router-4q_HAS_IMAGE_METADATA:=1
DEVICE_xiaomi_mi-router-4q_SUPPORTED_DEVICES:=xiaomi,mi-router-4q
DEVICE_xiaomi_mi-router-4q_PACKAGES:=
DEVICE_yuncore_a770_NAME:=YunCore A770
DEVICE_yuncore_a770_HAS_IMAGE_METADATA:=1
DEVICE_yuncore_a770_SUPPORTED_DEVICES:=yuncore,a770
DEVICE_yuncore_a770_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca9887-ct
DEVICE_yuncore_a782_NAME:=YunCore A782
DEVICE_yuncore_a782_HAS_IMAGE_METADATA:=1
DEVICE_yuncore_a782_SUPPORTED_DEVICES:=yuncore,a782
DEVICE_yuncore_a782_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca9888-ct
DEVICE_yuncore_xd4200_NAME:=YunCore XD4200
DEVICE_yuncore_xd4200_HAS_IMAGE_METADATA:=1
DEVICE_yuncore_xd4200_SUPPORTED_DEVICES:=yuncore,xd4200
DEVICE_yuncore_xd4200_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca9888-ct
DEVICE_zbtlink_zbt-wd323_NAME:=ZBT WD323
DEVICE_zbtlink_zbt-wd323_HAS_IMAGE_METADATA:=1
DEVICE_zbtlink_zbt-wd323_SUPPORTED_DEVICES:=zbtlink,zbt-wd323
DEVICE_zbtlink_zbt-wd323_PACKAGES:=kmod-usb2 kmod-i2c-core kmod-i2c-gpio kmod-rtc-pcf8563 kmod-usb-serial kmod-usb-serial-cp210x uqmi
DEVICE_devolo_dvl1200e_NAME:=devolo WiFi pro 1200e
DEVICE_devolo_dvl1200e_HAS_IMAGE_METADATA:=1
DEVICE_devolo_dvl1200e_SUPPORTED_DEVICES:=devolo,dvl1200e
DEVICE_devolo_dvl1200e_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_devolo_dvl1200i_NAME:=devolo WiFi pro 1200i
DEVICE_devolo_dvl1200i_HAS_IMAGE_METADATA:=1
DEVICE_devolo_dvl1200i_SUPPORTED_DEVICES:=devolo,dvl1200i
DEVICE_devolo_dvl1200i_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_devolo_dvl1750c_NAME:=devolo WiFi pro 1750c
DEVICE_devolo_dvl1750c_HAS_IMAGE_METADATA:=1
DEVICE_devolo_dvl1750c_SUPPORTED_DEVICES:=devolo,dvl1750c
DEVICE_devolo_dvl1750c_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_devolo_dvl1750e_NAME:=devolo WiFi pro 1750e
DEVICE_devolo_dvl1750e_HAS_IMAGE_METADATA:=1
DEVICE_devolo_dvl1750e_SUPPORTED_DEVICES:=devolo,dvl1750e
DEVICE_devolo_dvl1750e_PACKAGES:=kmod-usb2 kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_devolo_dvl1750i_NAME:=devolo WiFi pro 1750i
DEVICE_devolo_dvl1750i_HAS_IMAGE_METADATA:=1
DEVICE_devolo_dvl1750i_SUPPORTED_DEVICES:=devolo,dvl1750i
DEVICE_devolo_dvl1750i_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_devolo_dvl1750x_NAME:=devolo WiFi pro 1750x
DEVICE_devolo_dvl1750x_HAS_IMAGE_METADATA:=1
DEVICE_devolo_dvl1750x_SUPPORTED_DEVICES:=devolo,dvl1750x
DEVICE_devolo_dvl1750x_PACKAGES:=kmod-ath10k-ct ath10k-firmware-qca988x-ct
DEVICE_etactica_eg200_NAME:=eTactica EG200
DEVICE_etactica_eg200_HAS_IMAGE_METADATA:=1
DEVICE_etactica_eg200_SUPPORTED_DEVICES:=etactica,eg200 rme-eg200
DEVICE_etactica_eg200_PACKAGES:=kmod-usb-chipidea2 kmod-ledtrig-oneshot kmod-usb-serial kmod-usb-serial-ftdi kmod-usb-storage kmod-fs-ext4
DEVICE_jjplus_ja76pf2_NAME:=jjPlus JA76PF2
DEVICE_jjplus_ja76pf2_HAS_IMAGE_METADATA:=1
DEVICE_jjplus_ja76pf2_SUPPORTED_DEVICES:=jjplus,ja76pf2 ja76pf2
DEVICE_jjplus_ja76pf2_PACKAGES:=-kmod-ath9k -swconfig -wpad-mini -uboot-envtools fconfig
