#!/bin/bash

# led (C) Hak5 2018
# Usage: led <color|reset> [on|off]

if [[ $(cat /proc/cpuinfo | grep 'machine' | awk {'print $6'}) == "NANO" ]]; then
    device="NANO"
elif [[ $(cat /proc/cpuinfo | grep 'machine' | awk {'print $6'}) == "TETRA" ]]; then
    device="TETRA"
fi

usage() {
	echo "Usage: led <color|reset> [on|off]"
	echo " "
	if [[ $device == "NANO" ]]; then
		echo "Available colors are: BLUE"
	elif [[ $device == "TETRA" ]]; then
		echo "Available colors are: YELLOW, BLUE or RED"
	fi
}

resetLEDs() {
	/etc/init.d/led restart
}

enableLED() {
	led=$1
	if [[ $device == "NANO" ]]; then
		if [[ $led == "blue" ]] || [[ $led == "BLUE" ]] || [[ $led == "all" ]] || [[ $led == "ALL" ]]; then
			echo "255" > /sys/class/leds/wifi-pineapple-nano:blue:system/brightness
		else
			usage
		fi
	elif [[ $device == "TETRA" ]]; then
		if [[ $led == "all" ]] || [[ $led == "ALL" ]]; then
			echo "255" > /sys/class/leds/pineapple-tetra:yellow:eth0/brightness
/			echo "255" > /sys/class/leds/pineapple-tetra:blue:system/brightness
			echo "255" > /sys/class/leds/pineapple-tetra:red:wlan1mon/brightness
		elif [[ $led == "yellow" ]] || [[ $led == "YELLOW" ]]; then
			echo "255" > /sys/class/leds/pineapple-tetra:yellow:eth0/brightness
		elif [[ $led == "blue" ]] || [[ $led == "BLUE" ]]; then
			echo "255" > /sys/class/leds/pineapple-tetra:blue:system/brightness
		elif [[ $led == "red" ]] || [[ $led == "RED" ]]; then
			echo "255" > /sys/class/leds/pineapple-tetra:red:wlan1mon/brightness
		else
			usage
		fi
	fi
}

disableLED() {
	led=$1
	if [[ $device == "NANO" ]]; then
		if [[ $led == "blue" ]] || [[ $led == "BLUE" ]] || [[ $led == "all" ]] || [[ $led == "ALL" ]]; then
			echo "0" > /sys/class/leds/wifi-pineapple-nano:blue:system/brightness
		else
			usage
		fi
	elif [[ $device == "TETRA" ]]; then
		if [[ $led == "all" ]] || [[ $led == "ALL" ]]; then
			echo "0" > /sys/class/leds/pineapple-tetra:yellow:eth0/brightness
			echo "0" > /sys/class/leds/pineapple-tetra:blue:system/brightness
			echo "0" > /sys/class/leds/pineapple-tetra:red:wlan1mon/brightness
		elif [[ $led == "yellow" ]] || [[ $led == "YELLOW" ]]; then
			echo "0" > /sys/class/leds/pineapple-tetra:yellow:eth0/brightness
		elif [[ $led == "blue" ]] || [[ $led == "BLUE" ]]; then
			echo "0" > /sys/class/leds/pineapple-tetra:blue:system/brightness
		elif [[ $led == "red" ]] || [[ $led == "RED" ]]; then
			echo "0" > /sys/class/leds/pineapple-tetra:red:wlan1mon/brightness
		else
			usage
		fi
	fi
}

run() {
	color=$1
	mode=$2

	if [[ $color == "reset" ]] || [[ $mode == "RESET" ]]; then
		resetLEDs
		echo "Done."
		exit 0
	fi

	if [[ $mode == "on" ]] || [[ $mode == "ON" ]]; then
		enableLED $color
	elif [[ $mode == "off" ]] || [[ $mode == "OFF" ]]; then
		disableLED $color
	else
		usage
	fi
}

run $1 $2
echo "Done."
exit 0
